### ISSUE TITLE
problem running the code

### ISSUE THREAD

**Issue by haniehkh18** [SeungyounShin/Llama2-Code-Interpreter#10]
I get the below error when I run the command in Windows:
 C:\Data\Llama2-Code-Interpreter\code_interpreter\GPTCodeInterpreter.py:24 in <module>            │
│                                                                                                  │
│    21 from termcolor import colored                                                              │
│    22                                                                                            │
│    23 # load from key file                                                                       │
│ ❱  24 with open('./openai_api_key.txt') as f:                                                    │
│    25 │   OPENAI_API_KEY = key = f.read()                                                        │
│    26 openai.api_key = OPENAI_API_KEY                                                            │
│    27 from utils.cleaner import clean_error_msg                                                  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
FileNotFoundError: [Errno 2] No such file or directory: './openai_api_key.txt'

**Comment by cjie888** [comment]
Same with the mac.

**Comment by SeungyounShin** [comment]
Adding HF model. So no need to import openai_api_key.txt anymore I will rebase the code as soon as possible. thxs
