### ISSUE TITLE
HumanEval detail?

### ISSUE THREAD

**Issue by NicholasCao** [SeungyounShin/Llama2-Code-Interpreter#13]
Demonstrates the results of the humaneval
Model | Score(pass@1)
-- | --
Codellama instruct 7b | 34.8%
Codellama instruct 7b - finetuning | 70.12%

More details are needed here, recently wizardcoder required 34B to achieve similar performance, and achieving this performance in a 7B model is quite impressive.

Incidentally, will the training data be open source?

**Comment by itsPreto** [comment]
Agreed, it makes me think the benchmark could've been leaked into the fine-tune and overfitted.

@SeungyounShin I having issues getting the model to stick to a predictable format for python code but it's not very good at following instructions-- what is the format for identifying code within is completion?

**Comment by SeungyounShin** [comment]
Hi @NicholasCao,

To reproduce the results, you can run the following command:
```bash
python3 -m eval.human_eval --path <HF-7B-PATH>
```

I'm considering submitting this as a paper. Rest assured, the data will be made available shortly after publication.

**Comment by NicholasCao** [comment]
You mentioned `MAX_RETRY`, so it's not strictly pass@1 as I understand it?

**Comment by SeungyounShin** [comment]
@NicholasCao The model does not produce varied output for the same question, even when queried multiple times. This suggests that it operates in a single iteration, or 'one-hop', rather than using a multi-hop approach. It's as if the OPENAI Advanced Data Analysis model is designed to generate and execute the code within just one step.

**Comment by NicholasCao** [comment]
It seems that I have a little misunderstanding of MAX_RETRY, thanks for the answer, I will take a closer look at the code.
