### ISSUE TITLE
cant

### ISSUE THREAD

**Issue by willshion** [SeungyounShin/Llama2-Code-Interpreter#17]

**Comment by willshion** [comment]
<img width="400" alt="681eeea261a50ff47b757bbf603c811" src="https://github.com/SeungyounShin/Llama2-Code-Interpreter/assets/13349979/f0b64946-f267-4991-8528-5c2c00e86199">
like this

**Comment by SeungyounShin** [comment]
Please provide detail of description

**Comment by willshion** [comment]
mbbp  and human-val  comparartion  chart
