### ISSUE TITLE
Gradio UI

### ISSUE THREAD

**Issue by SeungyounShin** [SeungyounShin/Llama2-Code-Interpreter#3]
- [ ] Streaming 
- [ ]  Improve Chat window size 
- [ ]  Markdown also , latex support
- [ ]  Adding Upload files (saved at tmp -> partially done) then add to prompt
- [ ]  Code gen, exec hide? (will reduce chatting length and increase visibility)
- [ ] Show ![]() results

**Comment by warjiang** [comment]
Nice job. Any volunteers or contribution guide? want to make some help for this repo.

**Comment by SeungyounShin** [comment]
close [streaming added]
